
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def create_pdf_report(filename, data, language_code='en'):
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
    story = []
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#667eea'),
        alignment=1, # Center
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        alignment=1,
        spaceAfter=30
    )
    
    section_header_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading3'],
        fontSize=14,
        textColor=colors.white,
        backColor=colors.HexColor('#667eea'),
        borderPadding=6,
        spaceBefore=15,
        spaceAfter=10
    )
    
    normal_style = styles["Normal"]

    # --- Content Building ---
    story.append(Paragraph(f"Bid Analysis Report", title_style))
    story.append(Paragraph(f"Generated by Bid Analyser Pro - Language: {language_code.upper()}", subtitle_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"<b>EXECUTIVE SUMMARY</b>", section_header_style))
    summary_text = data.get('Executive_Summary', 'No summary available.')
    story.append(Paragraph(summary_text, normal_style))
    story.append(Spacer(1, 10))

    def create_section_table(data_dict):
        table_data = []
        for label, val in data_dict.items():
            if isinstance(val, list):
                val = ", ".join(val)
            table_data.append([Paragraph(f"<b>{label}</b>", normal_style), Paragraph(str(val), normal_style)])
        
        t = Table(table_data, colWidths=[2.5*inch, 4.5*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f8f9fa')),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.grey),
            ('BOX', (0, 0), (-1, -1), 0.25, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        return t

    story.append(Paragraph("<b>BASIC INFORMATION</b>", section_header_style))
    basic_info = {
        "Tender Reference": data.get("Tender_Reference"),
        "Issuing Authority": data.get("Issuing_Authority"),
        "Project Name": data.get("Project_Name")
    }
    story.append(create_section_table(basic_info))

    doc.build(story)
    print(f"Test Report saved: {filename}")

dummy_data = {
    "Tender_Reference": "TEST-2025",
    "Issuing_Authority": "Test Authority",
    "Project_Name": "Test Project",
    "Executive_Summary": "This is a test summary."
}

create_pdf_report("test_output.pdf", dummy_data)
